name: ds
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - python=3.8
  - requests
  - pip
  - mlflow
  - hydra-core
  - jupyter
  - jupyterlab
  - pytorch
  - scikit-learn
  - scipy
  - numpy
  - pandas
  - pandas-datareader
  - matplotlib
  - seaborn
  - cython
  - nltk
  - numba
  - pillow
  - scikit-image
  - tqdm
  - posix
  - pip:
      - protobuf
      - opencv-python
      - opencv-contrib-python
      - onnx
      - onnxruntime
      - torch
      - torchvision
      - torchaudio
      - tensorflow
      - chardet
      - hydra-joblib-launcher
      - wandb
      - autopep8
      - joblib
      - pytest
      - setuptools
      - wheel
      - spacy
      - imutils
