name: sam
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - requests
  - jupyter
  - jupyterlab
  - scikit-learn
  - scipy
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - cython
  - nltk
  - numba
  - pillow
  - pip:
      - protobuf
      - opencv-python
      - opencv-contrib-python
      - onnx
      - onnxruntime
      - onnx-simplifier
      - wandb
      - autopep8
      - joblib
      - pytest
      - setuptools
      - wheel
      - imutils